#ifndef VERSION_H
#define VERSION_H

#define MAIN_VERSION_MAJOR 1
#define MAIN_VERSION_MINOR 3
#define MAIN_VERSION_PATCH 0

#define MAIN_VERSION_BETA 0
#define MAIN_VERSION_DATE "2026-02-20"

#endif
